version: "2"
run:
  timeout: 5m
  concurrency: 8
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard_v2
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - interfacebloat
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
  exclusions:
    generated: lax
    rules:
      - path: _test\.go$
        linters:
          - goconst
          - gosec
          - dupl
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
