# Information
site_name: Yokai
site_url: https://ankorstore.github.io/yokai
site_description: >-
  Yokai: a simple, modular, and observable Go framework.

# Repository
repo_name: ankorstore/yokai
repo_url: https://github.com/ankorstore/yokai

# Plugins
plugins:
  - search
  - glightbox

# Theme
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  favicon: 'assets/images/favicon.ico'
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.expand
    - navigation.footer
    - search.highlight

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - tables

# Extra
extra_css:
  - 'assets/stylesheets/extra.css'

# Pages tree
nav:
  - "Overview": 'index.md'
  - "Getting started":
      - "Templates": applications/templates.md
  - "Demos":
      - "Showroom": applications/showroom.md
  - "Modules":
      - "Core": modules/fxcore.md
      - "Config": modules/fxconfig.md
      - "Generate": modules/fxgenerate.md
      - "Health Check": modules/fxhealthcheck.md
      - "HTTP Client": modules/fxhttpclient.md
      - "HTTP Server": modules/fxhttpserver.md
      - "Log": modules/fxlog.md
      - "Metrics": modules/fxmetrics.md
      - "ORM": modules/fxorm.md
      - "Trace": modules/fxtrace.md
      - "Worker": modules/fxworker.md
