name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          command: manifest
          monorepo-tags: true
          separate-pull-requests: true
          release-type: "go"
          tag-separator: "/"
