name: "worker-ci"

on:
    push:
        branches:
            - "feat**"
            - "fix**"
            - "hotfix**"
            - "chore**"
        paths:
            - "worker/**.go"
            - "worker/go.mod"
            - "worker/go.sum"
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
        branches:
            - main
        paths:
            - "worker/**.go"
            - "worker/go.mod"
            - "worker/go.sum"

jobs:
    ci:
        uses: ./.github/workflows/common-ci.yml
        secrets: inherit
        with:
            module: "worker"
            go_version: "1.26"
            linter_version: "1.64.8"
